#pragma once

#include <array>
#include <map>
#include <string>
#include <vector>

#include <QDialog>
#include <QImage>
#include <QPixmap>
#include <QPoint>
#include <QString>
#include <utility>

#include <Eigen/Dense>
#include <opencv2/core.hpp>

#include "Measure3dSession.h"
#include "Measure3dTypes.h"
#include "Moildev.h"
#include "PanelCornerRecovery.h"

class AxisRosClient;
class CameraRosClient;
class Point3dGlView;
class QCheckBox;
class QLabel;
class QLineEdit;
class QComboBox;
class QDoubleSpinBox;
class QPushButton;
class QSpinBox;
class QScrollArea;
class QObject;
class QEvent;
class QCloseEvent;
class QShowEvent;
class QTimer;

namespace Ui {
class sub_dialog_auto_3d_measurement;
class Form;
}

// Port of mvc_controller/controller_auto_3d_measurement.py (Controller3dMeasurement).
//
// Two-camera (left/right), checkerboard-based fisheye 3D dialog. The layout is
// UI3d_measurement.h (generated by uic from ui/UI3d_measurement.ui): the mid
// camera is gone and the whole form is wrapped in a scroll area so it fits a
// small monitor. This class still reproduces the Python controller's behaviour,
// reaching every widget by the same object name, and uses the native Moildev
// SDK port + AnypointChessboard + PlaneFit3dViz engines.
//
// The (axis, camera) clients are kept for MainWindow API compatibility but are
// unused by this offline, image-driven workflow.
class Controller3dMeasurement : public QDialog {
    Q_OBJECT
public:
    Controller3dMeasurement(AxisRosClient *axis, CameraRosClient *cam, QWidget *parent = nullptr);
    ~Controller3dMeasurement() override;

protected:
    bool eventFilter(QObject *source, QEvent *event) override;
    void showEvent(QShowEvent *event) override;    // where the restore prompt belongs
    void closeEvent(QCloseEvent *event) override;  // last chance to autosave

private:
    enum { LEFT = 0, RIGHT = 1};

    // ---- setup ----
    void connectBtnEvent();
    void initSpinboxFromDefaultAngles();
    void connectSpinboxes();
    void populateReorderCombos();
    void makeLabelClickable(QLabel *label);

    // ---- pipeline (mirrors the Python methods) ----
    void onclickOpenMedia(int pos);
    void onclickOpenParameter(int pos);
    bool createMoildev(int pos, const std::string &paramPath);
    void readImageSource(int pos, const std::string &imagePath, const std::string &paramPath);
    void generateAllAnypointForPosition(int pos);
    void generateOneAnypointRemap(int pos, const std::string &camKey, const std::string &direction);
    void detectCheckerboardAnypoint(const std::string &camKey, const std::string &direction);
    void overlayAllToFisheye(const std::string &camKey);
    cv::Mat combineFisheyeOverlay(const std::string &camKey);
    void handleStartCalculation();

    // Invalidation + auto-refresh when the image or camera parameters change.
    // The old detections (alpha/beta computed with the previous JSON) and the
    // joint 3D result no longer apply, so they are wiped; the directions that
    // were detected before are then re-detected (async, one at a time) and the
    // calculation is re-run, which is what makes the result actually update when
    // the parameter JSON is swapped. See onclickOpenParameter / onclickOpenMedia.
    void invalidateResults(int pos);
    void clearResultUi();
    std::vector<std::string> detectedDirections(const std::string &cam) const;
    void scheduleRedetect(int pos, const std::vector<std::string> &dirs);
    void driveRedetectQueue();

    // Auto framing for ONE (camera, direction): sweep zoom (+ small pitch/yaw
    // nudges) on a low-resolution anypoint to find a view where the checkerboard
    // (size from the direction's "poin" field, else asked) is detected, set the
    // winning angles/zoom/size into the UI, then run the normal full-resolution
    // detect. Invoked per direction from its own "Detect" button ("1 by 1").
    void autoDetectDirection(const std::string &cam, const std::string &dir);

    // ---- Exact Python API (controller_auto_3d_measurement.py), snake_case 1:1.
    // Python drives the axis + camera to capture live; the C++ port is an
    // offline, image-file workflow, so these live-capture methods are present
    // for name parity and are no-ops/structural offline (they need the axis +
    // camera + monitor hardware servers to function).
public:
    void onclick_btn_start();
    void auto_3d_measurement(const std::string &direction, int n);
    void onclick_btn_stop();
    void set_moniter_viewer(const std::string &direction);
    void control_cam_direction(const std::string &path, int n);
    static std::pair<int, int> get_random_point(int x_lower_limit, int x_upper_limit,
                                                int y_lower_limit, int y_upper_limit);
    static QImage cv2_image_to_q_image(const cv::Mat &bgr_image);

private:

    // ---- helpers ----
    std::array<double, 3> anglesFromUi(const std::string &camKey, const std::string &direction) const;
    std::pair<int, int> patternSizeFromUi(const std::string &camKey,
                                          const std::string &direction) const;
    void updateResolutionToUi(int pos);
    void showToUi();
    void show_image_to_label(QLabel *label, const cv::Mat &bgr, int width);
    void showPathToUi(int pos);
    void updateAngleToUi(const std::map<std::string, double> &m);
    void updateMeanDistToUi(const std::map<std::string, double> &m);
    void updatePlaneDistToUi(const std::map<std::string, double> &m);
    void updateDepthToUi(const std::map<std::string, double> &m);
    void overlayReprojection(int pos, const std::vector<Measure3d::ReprojRow> &rows);
    void ensure3dViewEmbedded();  // lazily place the GPU viewer in the "3D View" tab

    // ---- session cache (YAML) ----
    // Everything the dialog holds is captured into a Measure3d::Session and
    // written to disk: automatically to one autosave slot (on close, and 2 s
    // after each finished detection or calculation), or to a file of the user's
    // choosing via the Save/Load buttons. Opening the dialog offers to restore
    // the autosave. Images are referenced by path, never embedded.
    void buildSessionButtons();          // uses .ui buttons when they exist
    // Draw a stored detection back onto its anypoint view, so a restored session
    // shows its corners without the user pressing Detect again.
    void drawDetectionOnAnypoint(const std::string &camKey, const std::string &direction);
    Measure3d::Session captureSession() const;
    void applySession(const Measure3d::Session &s);
    void scheduleAutosave();             // debounced; call after any state change
    void writeAutosaveNow();
    void onclickSaveSession();
    void onclickLoadSession();
    void offerRestoreOnOpen();           // the "restore last session?" prompt

    // ---- ORI_DET: original-image 4-point plane calibration (tab_2 / tab_3) ----
    // The user clicks the 4 outermost-inner corners (TL,TR,BR,BL) of each plane on
    // the LEFT original image then the RIGHT, stepping through the 5 planes
    // (center,east,west,south,north). Start Calculation recovers the full corner
    // grid per plane, triangulates, and shows the 3D + metrics in tab_3. Built
    // programmatically because tab_2/tab_3 are empty placeholders in the .ui.
    void ensureOriDetTab();              // build tab_2 UI (once)
    void oriResetClicks();               // clear ALL captured points, back to step 0
    void oriDeletePlane(const std::string &plane);  // clear one plane (both cameras)
    void oriAdvanceStep();               // set the target to the first image still needing clicks
    void oriHandleClick(int pos, QPoint labelPos);  // place one corner point
    void oriShowPanels();                // redraw both images + their click markers
    // One panel drawn at an arbitrary resolution (original px per rendered px):
    // the panel uses origW/520, the fullscreen viewer asks for 1.0.
    cv::Mat oriRenderPanel(int pos, double scale);
    void oriRecoverPlane(const std::string &plane, int cam);  // 4 clicks -> corners (per image)
    void oriUpdateCounts();              // per-camera "plane: CxR - N corners" labels
    void oriUpdatePrompt(bool popup);    // refresh status text (+ optional QMessageBox)
    // Highlight the plane being asked for among the direction names that sit
    // around each image (never drawn ON the image, so nothing is covered).
    void oriHighlightDirection(const std::string &curPlane);
    void oriStartCalculation();          // recover corners -> triangulate -> metrics
    // Whole-image survey: find every board in both images with no clicking and
    // re-detect each one with every method, then draw the results on top of each
    // other in different colours so they can be compared directly. This is the
    // tool for "which detector actually reaches the corners near a panel edge".
    void oriSurveyRun();
    void oriSurveyRefreshLegend();
    void ensureOriResultTab();           // build tab_3 (GL view + fixed metrics panel)
    void oriShowResults(const std::map<std::string, double> &angles,
                        const std::map<std::string, double> &interRay,
                        const std::map<std::string, double> &thickness,
                        const std::map<std::string, double> &depth, double meanErrL, double rmsL,
                        double meanErrR, double rmsR);
    QPoint oriLabelToImage(int pos, QPoint labelPos) const;  // scaled label -> orig px

    static const std::vector<std::string> kOriPlaneOrder;  // center,east,west,south,north
    static const std::array<const char *, 4> kOriCornerLabels;  // TL,TR,BR,BL

    // ---- fullscreen viewer (ports show_fullscreen_image + _fs_*) ----
    void showFullscreenImage(QLabel *label);
    void closeFullscreenImage();
    void fsFitToView();
    void fsZoomImage(double factor, QPoint anchor);

    // widget accessors by Python object name
    QDoubleSpinBox *spin(const std::string &axis, const std::string &cam, const std::string &dir) const;
    QLineEdit *pointEdit(const std::string &cam, const std::string &dir) const;
    QComboBox *reorderCombo(const std::string &cam, const std::string &dir) const;
    QLabel *anyLabel(const std::string &cam, const std::string &dir) const;
    int posOf(const std::string &camKey) const;

    static const std::vector<std::string> kCameras;    // left, right
    static const std::vector<std::string> kDirections; // center,north,south,west,east

    Ui::sub_dialog_auto_3d_measurement *ui_;
    Ui::Form *uiFull_;
    QWidget *fullscreenWindow_ = nullptr;

    AxisRosClient *axis_;
    CameraRosClient *cam_;

    // ---- model state ----
    std::array<Moildev, 3> moil_;
    std::array<cv::Mat, 3> imageSource_;        // BGR fisheye
    std::array<std::string, 3> imagePath_, paramPath_;
    std::map<std::string, std::map<std::string, cv::Mat>> grayAnypoint_;
    std::map<std::string, std::map<std::string, cv::Mat>> anypointImages_;  // BGR for display
    // Cached (mapX, mapY) anypoint remap tables per [cam][dir], built once in
    // generateOneAnypointRemap and reused by Detect so mapsAnypointMode2 (the
    // dense per-pixel transform) is not recomputed for the same angles.
    std::map<std::string, std::map<std::string, std::pair<cv::Mat, cv::Mat>>> anypointMaps_;
    std::map<std::string, std::map<std::string, Measure3d::DetectionResult>> detection_;
    std::array<cv::Mat, 3> resultDraw_, resultDrawOverOri_;

    // Last triangulation result, kept so the in-app GPU 3D viewer can show it.
    std::vector<Measure3d::Point3d> points3d_;
    Eigen::Vector3d camL3d_{Eigen::Vector3d::Zero()}, camR3d_{Eigen::Vector3d::Zero()};
    Point3dGlView *glView_ = nullptr;  // embedded in the "Result 2 Camera" tab

    // Last anypoint metrics, kept only so a restored session can show its numbers
    // without re-running anything (the line edits themselves are not readable
    // back into doubles reliably).
    std::map<std::string, double> lastAngle_, lastInterRay_, lastThickness_, lastDepth_;
    double lastMeanErrL_ = Measure3d::nan(), lastRmsL_ = Measure3d::nan(),
           lastMeanErrR_ = Measure3d::nan(), lastRmsR_ = Measure3d::nan();
    // Same for the ORI_DET tab.
    std::map<std::string, double> oriAngle_, oriInterRay_, oriThickness_, oriDepth_;
    double oriMeanErrL_ = Measure3d::nan(), oriRmsL_ = Measure3d::nan(),
           oriMeanErrR_ = Measure3d::nan(), oriRmsR_ = Measure3d::nan();

    // Session cache plumbing.
    QTimer *autosaveTimer_ = nullptr;  // debounces bursts of state changes
    bool restoring_ = false;           // suppress autosaves while applying a session
    bool restorePromptShown_ = false;  // ask once, on the first show
    QPushButton *btnSaveSession_ = nullptr, *btnLoadSession_ = nullptr;
    QLabel *sessionStatus_ = nullptr;

    // True while a checkerboard detection runs on a worker thread. Serialises
    // detection and blocks the paths that touch the shared detection buffer /
    // reload Moildev, so the worker never races with the UI thread.
    bool detecting_ = false;

    // Sequential re-detection queue used after the image/parameters change: each
    // (cam, direction) is detected on the worker, and when the queue drains a
    // recalculation runs if recalcAfterRedetect_ is set. Driven from the detect
    // finished-callback so only one worker runs at a time (respects detecting_).
    std::vector<std::pair<std::string, std::string>> pendingRedetect_;
    bool recalcAfterRedetect_ = false;

    QString autoBoardSize_ = "6x5";  // last board size the user typed for auto framing

    // ---- ORI_DET state ----
    // oriClicks_[plane][cam] = up to 4 corner points in ORIGINAL image pixels.
    std::map<std::string, std::array<std::vector<cv::Point2f>, 2>> oriClicks_;
    int oriStepPlane_ = 0;              // index into kOriPlaneOrder
    int oriStepCam_ = 0;               // LEFT first, then RIGHT, per plane
    QLabel *oriLabel_[2] = {nullptr, nullptr};   // left/right image panels
    QScrollArea *oriScroll_[2] = {nullptr, nullptr};  // sized to the picture (labels hug it)
    QLabel *oriCaption_[2] = {nullptr, nullptr}; // big "LEFT IMAGE" / "RIGHT IMAGE" headers
    QLabel *oriCount_[2] = {nullptr, nullptr};   // "plane: CxR - N corners" under each image
    QLabel *oriStatus_ = nullptr;      // prompt text above the panels
    // Direction names framing each image panel: [cam][plane] -> label. Fixed
    // text (SOUTH above, NORTH below, WEST left, EAST right, CENTER in the free
    // corner); only the highlight moves as the workflow steps through planes.
    std::map<std::string, QLabel *> oriDirLabels_[2];
    // Auto-detected inner-corner grid per [plane][cam] (red X overlay + counts).
    // Each plane can have a different board size (detected from its 4 clicks).
    std::map<std::string, std::array<PanelCorner::PanelDetection, 2>> oriRecovered_;
    // Curved fisheye boundary polyline per [plane][cam] (original px).
    std::map<std::string, std::array<std::vector<cv::Point2f>, 2>> oriBoundary_;
    // Reprojected pixels per camera (blue + overlay) from the last calculation.
    std::vector<Measure3d::ReprojRow> oriReproj_[2];
    double oriScale_[2] = {1.0, 1.0};  // origW / displayedW per panel
    QSpinBox *oriRows_ = nullptr, *oriCols_ = nullptr;  // grid size (inner corners)
    // Corner detector the user picked in the ORI_DET tab. Auto runs the measured
    // cascade; the named ones are there so a plane that one method mis-reads can
    // be redone with another (and so the methods can be compared on real data).
    QComboBox *oriMethodCombo_ = nullptr;
    PanelCorner::Method oriMethod_ = PanelCorner::Method::Auto;
    // Whether the point index is written beside each detected corner. Auto keeps
    // it off when the corners are too close together to read it at panel size.
    enum { IndexAuto = 0, IndexAlways = 1, IndexNever = 2 };
    QComboBox *oriIndexModeCombo_ = nullptr;
    int oriIndexMode_ = IndexAuto;
    // Each overlay layer can be taken off on its own, so a dense board can be
    // inspected without the marks that describe it. Detection is unaffected --
    // this is purely what gets drawn.
    QCheckBox *oriShowCornersBox_ = nullptr, *oriShowReprojBox_ = nullptr,
              *oriShowOutlineBox_ = nullptr;
    bool oriShowCorners_ = true;  // red X + its index
    bool oriShowReproj_ = true;   // blue + from the last calculation
    bool oriShowOutline_ = true;  // the 4 clicks + the quad/boundary joining them

    // ---- whole-image survey (the "Detect All" button) ----
    QPushButton *oriSurveyBtn_ = nullptr;
    QComboBox *oriSurveyLayerCombo_ = nullptr;  // which layer(s) to draw
    QLabel *oriSurveyLegend_ = nullptr;         // colour key + per-method counts
    std::array<std::vector<PanelCorner::SurveyLayer>, 2> oriSurvey_;
    int oriSurveyShow_ = -1;      // -1 = draw every layer
    bool oriSurveying_ = false;   // a survey is running on the worker thread
    Point3dGlView *oriGlView_ = nullptr;         // embedded in tab_3
    QWidget *oriMetricsHost_ = nullptr;          // holds the fixed metrics panel in tab_3
    std::vector<Measure3d::Point3d> oriPoints3d_;  // last ORI_DET triangulation
    Eigen::Vector3d oriCamL_{Eigen::Vector3d::Zero()}, oriCamR_{Eigen::Vector3d::Zero()};

    // fullscreen viewer state
    std::map<QLabel *, QPixmap> fullPixmap_;
    QScrollArea *fsSa_ = nullptr;
    QLabel *fsLab_ = nullptr;
    QPixmap fsPixmap_;
    double fsZoom_ = 1.0;
    bool fsDragging_ = false;
    QPoint fsLastMouse_;
};
