@echo off
REM Build the MoilCali server.
REM Double-click this, or run it from any shell. It needs no editing.
REM
REM Everything this script needs is found by scripts\moil_env.bat rather than
REM written down here: Qt, OpenCV, the ROS distro and MSVC are searched for, and
REM every path inside the workspace is derived from this file's own location. Run
REM
REM   scripts\moil_env.bat --check
REM
REM to see what it resolved. To override one of them on your machine, copy
REM deps.local.bat.example to deps.local.bat -- do not edit this file.
REM
REM STOP THE SERVER BEFORE BUILDING. If it is running, the build fails with
REM "Permission denied" because the moil_interfaces DLL is in use.
REM
REM The build output does NOT land in this folder. It goes to a short path off
REM the drive root (C:\moil_ws by default) because Windows caps a path at 260
REM characters and rosidl nests about 120 characters deep on its own -- see
REM :resolve_ws in scripts\moil_env.bat. run_server.bat reads the same location
REM from the same script, so the two cannot disagree.

REM --need-msvc: this script compiles, so a missing Visual Studio is fatal HERE.
REM The scripts that only run things ask without it and start fine without a
REM compiler on the machine.
call "%~dp0scripts\moil_env.bat" --need-msvc
if errorlevel 1 exit /b 1

REM The ROS tools live inside the pixi environment; outside it neither colcon nor
REM ros2 exists. Re-run this same script within it, once. PIXI_MANIFEST is empty
REM when ROS is already on PATH, and then there is nothing to re-exec into.
if defined PIXI_IN_SHELL goto :main
if not defined PIXI_MANIFEST goto :main
set "PATH=%LOCALAPPDATA%\pixi\bin;%PATH%"
pixi run --manifest-path "%PIXI_MANIFEST%" cmd /c "%~f0" %*
exit /b %ERRORLEVEL%

:main
REM 2>nul as well as >nul. vcvars64.bat is Microsoft's script, and on a
REM Build Tools install it prints "'vswhere.exe' is not recognized" to stderr on
REM its way to setting the environment correctly anyway. Left visible it is the
REM first thing in the build log, it names a tool this script also uses, and it
REM sends whoever is reading a failed build off after the wrong thing.
call "%VCVARS%" >nul 2>nul
set ROS_DOMAIN_ID=42
if defined ROS_LOCAL_SETUP call "%ROS_LOCAL_SETUP%"

REM Qt is pointed at with Qt6_DIR, NOT -DCMAKE_PREFIX_PATH.
REM
REM That is not a style choice. colcon builds moil_interfaces first and then puts
REM its install space on CMAKE_PREFIX_PATH so moil_server can find it. Passing
REM -DCMAKE_PREFIX_PATH on the command line REPLACES that, and the second package
REM then fails with "Could not find a package configuration file provided by
REM moil_interfaces" -- which reads like the interfaces did not build, when in
REM fact they built fine and were merely hidden.
set "Qt6_DIR=%QT_CMAKE_DIR%"
set "OpenCV_DIR=%OPENCV_DIR%"

cd /d "%~dp0"

REM One build tree per source tree.
REM
REM The build root is outside the workspace and shared by default, so two
REM checkouts would otherwise write into each other -- and a stale CMake cache
REM there fails by pointing the compiler at the OTHER tree's sources, which
REM compiles and produces a binary built from code you are not looking at.
REM The stamp records which tree owns this build root; a mismatch wipes it.
if not exist "%MOIL_WS_BASE%" mkdir "%MOIL_WS_BASE%" 2>nul
if not exist "%MOIL_WS_BASE%" (
  echo Cannot create the build root %MOIL_WS_BASE%.
  echo Set MOIL_WS_BASE to a short writable path in deps.local.bat.
  goto :failed
)
REM Read the stamp with set /p and compare it as a string.
REM
REM NOT findstr. The path being matched ends in a backslash, and `findstr
REM /c:"...\server\"` hands the argument parser a \" pair -- an escaped quote --
REM so the search string runs on into the next argument and never matches. Every
REM build then declared the build root stale and wiped it, which turned every
REM incremental build into a five-minute clean one and looked like colcon
REM failing to cache.
REM
REM /i, because the thing being compared is a WINDOWS PATH and Windows does not
REM distinguish its case. `if` does. Double-clicking this file gives %~dp0 a
REM capital drive letter and launching it from a shell can give a lower-case one,
REM so the same folder wrote "C:\Users\..." and read back "c:\Users\..." -- the
REM compare failed, the build root was declared foreign, and every second build
REM wiped the previous one's work. That is the exact failure the findstr note
REM above describes, arrived at a second way, and it hides just as well: a clean
REM build succeeds, so nothing looks broken except the clock.
set "_STAMP="
if exist "%MOIL_WS_STAMP%" set /p _STAMP=<"%MOIL_WS_STAMP%"
if /i "%_STAMP%"=="%~dp0" goto :ws_ready
if not exist "%MOIL_BUILD_BASE%" goto :ws_ready
echo Build root %MOIL_WS_BASE% belongs to a different copy of this tree.
echo Clearing it so this build cannot pick up the other one's sources.
rmdir /s /q "%MOIL_BUILD_BASE%"   2>nul
rmdir /s /q "%MOIL_INSTALL_BASE%" 2>nul

:ws_ready
REM Redirection first, so the trailing backslash of %~dp0 is never the character
REM before a ">".
> "%MOIL_WS_STAMP%" echo %~dp0

REM TWO STAGES, with the interfaces' environment sourced in between.
REM
REM One `colcon build` over both packages does build them in the right order, but
REM it does not reliably put moil_interfaces' install prefix on CMAKE_PREFIX_PATH
REM for the package that follows -- and moil_server then fails with "Could not
REM find a package configuration file provided by moil_interfaces", which reads
REM like the interfaces did not build when in fact they built fine.
REM
REM Sourcing the install space between the two is explicit, always works, and is
REM what you would do by hand.

echo.
echo === 1/2  moil_interfaces (the contract) ===
REM Built from ros\moil_interfaces at the REPOSITORY ROOT, not from a copy under
REM this folder. That is the point: the client builds the same package from the
REM same files, so the two sides cannot drift.
REM
REM They must not. ROS matches services by type hash, so a definition differing by
REM one character makes every call of that service fail to connect -- while topics
REM keep flowing, so the rig looks alive and no button works. When there were two
REM copies, keeping them identical was a thing someone had to remember.
REM
REM This is the one path here that reaches outside the server tree, so it is
REM checked by name: without this the failure is colcon building zero packages and
REM then moil_server reporting that moil_interfaces does not exist, which reads
REM like a broken distro rather than a wrong path.
set "MOIL_INTERFACES_DIR=%~dp0..\..\ros\moil_interfaces"
if not exist "%MOIL_INTERFACES_DIR%\package.xml" (
  echo ERROR: moil_interfaces not found at "%MOIL_INTERFACES_DIR%".
  echo This server tree is built from inside the moil-fisheye-calisys repository,
  echo which holds the one copy of the interface package that the client uses too.
  goto :failed
)

colcon --log-base "%MOIL_LOG_BASE%" build --paths "%MOIL_INTERFACES_DIR%" ^
  --build-base "%MOIL_BUILD_BASE%" ^
  --install-base "%MOIL_INSTALL_BASE%" ^
  --cmake-args -DCMAKE_BUILD_TYPE=Release
if errorlevel 1 goto :failed

call "%MOIL_INSTALL_BASE%\setup.bat"

echo.
echo === 2/2  moil_server (the rig and the maths) ===
REM Eigen is added to the command line only when moil_env.bat actually found a
REM copy, which on a normal machine it does not: the ROS distro ships eigen3 in
REM its own environment and colcon already has that on CMAKE_PREFIX_PATH. The old
REM script passed -DEIGEN3_INCLUDE_DIR unconditionally and the CMake cache records
REM it UNINITIALIZED and unread -- configuration that looked load-bearing and was
REM not.
REM
REM Eigen3_DIR and NOT CMAKE_PREFIX_PATH, for the reason given above the Qt6_DIR
REM line: overriding CMAKE_PREFIX_PATH hides moil_interfaces from this package.
set "_EIGEN_ARG="
if defined EIGEN_DIR set "_EIGEN_ARG=-DEigen3_DIR=%EIGEN_DIR%\share\eigen3\cmake"

colcon --log-base "%MOIL_LOG_BASE%" build --paths "%~dp0packages\moil_server" ^
  --build-base "%MOIL_BUILD_BASE%" ^
  --install-base "%MOIL_INSTALL_BASE%" ^
  --cmake-args -DCMAKE_BUILD_TYPE=Release ^
               -DQt6_DIR="%QT_CMAKE_DIR%" ^
               -DOpenCV_DIR="%OPENCV_DIR%" %_EIGEN_ARG%
if errorlevel 1 goto :failed

echo.
echo BUILD_EXIT=0
echo Server built into %MOIL_INSTALL_BASE%
echo Start it with run_server.bat
pause
exit /b 0

:failed
echo.
echo BUILD_EXIT=%ERRORLEVEL%
echo.
echo The compiler's own output is NOT above -- colcon captures it per package.
echo It is in:
echo   %MOIL_LOG_BASE%\latest_build\^<package^>\stdout_stderr.log
echo.
echo The build failed. Three causes account for most of them:
echo   * the server is still running        -^> stop it, then build again
echo   * "Cannot open source file"          -^> the path is still too long;
echo                                           set MOIL_WS_BASE shorter in deps.local.bat
echo   * a dependency was found wrongly     -^> run scripts\moil_env.bat --check
pause
exit /b 1
